Rallamgsa patch 1
18F/hud-erm-ide-custom-api pull request #3
Opened 2021-02-05 19:50 UTC by rallamgsa

2021-02-08 14:45 UTC, rcoxGSA requested changes

2021-02-08 14:45 UTC, rcoxGSA commented on src/main/java/com/book/mark/service/impl/CreateBookmarksServiceImpl.java
> +				orderedMap.put("UnAssigned", unAssigPageList);
Change "UnAssigned"  to "Unassigned" since this ends up on the output

2021-02-11 19:44 UTC, rallamgsa commented
I made changes UnAssinged to Unassigned

2021-02-11 20:47 UTC, rcoxGSA approved these changes

2021-02-11 20:47 UTC, merged